[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npx prisma generate", "npm run build", "npm prune --production"]

[start]
cmd = "node dist/index.js"

[variables]
PORT = "3000"
NODE_ENV = "production"
